AMP-SCZ/lochness

lochness/mindlamp/__init__.py, lochness/rpms/__init__.py, lochness/transfer/__init__.py, scripts/lochness_create_template.py, scripts/sync.py, tests/lochness_test/mindlamp/test_mindlamp.py
Commits below represent a few changes made while testing `lochness` in the Prescient dev server. Most of the commits are minor fixes or features, but the `get_rpms_database` function is updated to take in a real example of RPMS exported csv file now.
=> Update from Prescient dev server

setup.py
Closes #45
Hi Kevin, it can be merged before PR #43 or after. If after, the head should automatically change to `master`. Regardless, please see what you think about the proposed installation strategy.
=> Install dpanonymize master

scripts/sync.py
=> Display sources list once

lochness/__init__.py, lochness/box/__init__.py, lochness/keyring/__init__.py, lochness/mindlamp/__init__.py, lochness/redcap/__init__.py, lochness/rpms/__init__.py, lochness/transfer/__init__.py, scripts/lochness_create_template.py, scripts/sync.py, setup.py, tests/lochness_test/box/test_box.py, tests/lochness_test/mindlamp/test_mindlamp.py, tests/lochness_test/rpms/test_rpms.py, tests/test_lochness.py
=> Revert "UPENN Cognitive battery REDCap option (redcap + redcap OR rpms + redcap)"

lochness/box/__init__.py, lochness/keyring/__init__.py, lochness/mindlamp/__init__.py, lochness/transfer/__init__.py, lochness/xnat/__init__.py, scripts/lochness_create_template.py, scripts/sync.py, tests/lochness_test/mindlamp/test_mindlamp.py, tests/lochness_test/xnat/test_xnat.py, tests/test_lochness.py
During a testing session of Pronet XNAT, I have faced with a problem with `lochness.xnat`. It was downloading a large amount of data, but only saving the last series of the scan session.
Providing `out_format='native'` to Yaxil.download has resolved the issue, and it now saves all series.
=> Fix for lochness.xnat module only saving the last MRI series

lochness/box/__init__.py, lochness/keyring/__init__.py, lochness/mindlamp/__init__.py, lochness/transfer/__init__.py, lochness/xnat/__init__.py, scripts/lochness_create_template.py, scripts/sync.py, tests/lochness_test/box/test_box.py, tests/lochness_test/mindlamp/test_mindlamp.py, tests/lochness_test/xnat/test_xnat.py, tests/test_lochness.py
Subdirectory structures under the box source to be kept in the downloaded structure.  eg) Entire zoom output directory will be pulled and the subdirectory structure of the zoom recording will be kept in the PHOENIX. (this version has been tested with zoom recording directories)
=> Box to keep subdirectory structure 

lochness/__init__.py, lochness/box/__init__.py
- Pronet REDCap record ID is "`chric_record_id`"
- For testing purposes, datatype directory root paths could be given as `PRONET_XX/TEST`.
=> feat: PRONET redcap record ID field name is 'chric_record_id' & box update

lochness/mediaflux/__init__.py, lochness/mindlamp/__init__.py, lochness/rpms/__init__.py, scripts/lochness_create_template.py, scripts/sync.py, tests/lochness_test/rpms/test_rpms.py
`all_df_dict` includes RPMS dataframes of all subjects from different sites. (In the last version, only single site dataframe has been considered.) Changes are made to make it work with `all_df_dict` that contains subjects from more than one sites.
=> Update metadata population from RPMS database

lochness/mindlamp/__init__.py
old comments helped me to identify the places where changes have been proposed in PR #60
=> bring back old comments to facilitate git diff

docs/source/index.rst, docs/source/quick_start.rst, docs/source/sync_in_detail.rst
Typos, grammar, and clarification only
Please merge it if appropriate.
=> Minor changes in doc files

docs/source/index.rst, docs/source/quick_start.rst, docs/source/sync_in_detail.rst, lochness/__init__.py, lochness/__version__.py, lochness/box/__init__.py, lochness/keyring/__init__.py, lochness/mediaflux/__init__.py, lochness/mindlamp/__init__.py, lochness/redcap/__init__.py, lochness/redcap/data_trigger_capture.py, lochness/redcap/process_piis.py, lochness/rpms/__init__.py, lochness/transfer/__init__.py, lochness/tree/__init__.py, lochness/xnat/__init__.py, scripts/lochness_check_config.py, scripts/lochness_create_template.py, scripts/sync.py, setup.cfg, setup.py, tests/lochness_test/box/test_box.py, tests/lochness_test/mindlamp/test_mindlamp.py, tests/lochness_test/redcap/test_redcap.py, tests/lochness_test/rpms/test_rpms.py, tests/lochness_test/xnat/test_xnat.py, tests/test_lochness.py
During the testing of the data flow on the Pronet server, I've edited different parts of the code to make the lochness work smoothly at least for the Pronet network. The changes represented in this PR are not on a single topic, but rather a broader fixes and updates. It deviated quite a bit from PR #56, so I'm submitting it as a separate PR here.
=> update from Pronet dev server

lochness/email/__init__.py
Description should come before configuration file example
TYPO: smpt-->SMTP
=> send_detail() docstring update

lochness/email/__init__.py
I just realized that `.iloc` cannot be used to replace values. I replaced `.iloc` to `.loc`.
=> fix: cannot define value with df.iloc

lochness/rpms/__init__.py
`lochness.rpms` updated to compare existing survey `.csv` files, before overwriting them. Previous logic was using `.mtime` approach, but now it's updated to compare source and target dataframes using `pandas.DataFrame.equals`.
=> feat: update logic for checking updates in RPMS table to use Pandas df.equals

lochness/rpms/__init__.py
This PR is for `lochness.rpms` to only keep the row with the most recent modification for each visit and each subject.
=> Keep the row with the most recent modification for each visit and subject

lochness/email/__init__.py, lochness/utils/source_check.py, scripts/sync.py
Source-file-check system is configured for Prescient. This PR requires
```
file_check_notify:
__global__:
- email@bwh.harvard.edu
```
=> Prescient network configured to send source-check email daily

lochness/email/__init__.py, lochness/redcap/__init__.py, lochness/rpms/__init__.py, lochness/transfer/__init__.py, lochness/utils/path_checker.py, scripts/send_email_update.py
This PR updates lochness for
- extracting the run sheets for prescient network (coded in a way to follow the structure of `lochness.redcap` run sheet extraction.)
A few minor additional updates
- to also double check if the site & the two letters in the AMPSCZ ID matches
- `send_email_update.py` function to also execute `check_source` email function
=> To extract run-sheets in Prescient RPMS outputs

lochness/email/__init__.py, lochness/redcap/__init__.py, lochness/rpms/__init__.py, lochness/transfer/__init__.py, lochness/utils/path_checker.py, scripts/send_email_update.py
Previous two PRs have been made against & merged into `kcho/prescient`. PR to master is needed to deploy it to Pronet `prod` server.
=> Merging into master

lochness/redcap/__init__.py
REDCap project may have a different primary key from the `redcap_id_colname` given in the configuration file. The current PR updates `record_query` to use `filterLogic` of given `redcap_id_colname` field rather than the default primary key of the REDCap. This will enable lochness to work with REDCap projects with a different primary key, as long as the project has data field of `redcap_id_colname` specified in the configuration file.
=> feat: to work with REDCap with different primary key

lochness/utils/path_checker.py, lochness/utils/source_check.py
1. To make sure `eeg` files are `.zip` files
2. Separate out `AMP-SCZ` ID check information from the `Format` column
=> Source file check email function minor update

lochness/__init__.py, lochness/redcap/__init__.py, lochness/redcap/data_trigger_capture.py, lochness/xnat/__init__.py
DET updated (tested in the production server)
- activated DET
- Load DET db only when needed (for the main study REDCap, but not for the `UPENN REDCap`)
- Lochness object contains `data_entry_trigger_csv` for each study. `get_data_entry_trigger_df` had been updated to account for this.
=> fix: DET working version

lochness/utils/source_check.py
PENN CNB REDCap is included in the source file check.
=> feat: PENN CNB REDCap included in the source file check

lochness/mediaflux/__init__.py, lochness/redcap/__init__.py, lochness/rpms/__init__.py, lochness/utils/source_check.py, tests/lochness_test/rpms/test_rpms.py
updates
- feat: run sheet to have digits in the file name
- fix: mediaflux to keep zoom folder structure
- skip pulling files when there is error in the RPMS exported CSV files.
=> Run sheet to have digits in the file name

lochness/config/__init__.py, lochness/mindlamp/__init__.py, lochness/redcap/__init__.py, lochness/redcap/data_trigger_capture.py, lochness/transfer/__init__.py, lochness/utils/checksum.py, lochness/utils/path_checker.py, lochness/utils/source_check.py, lochness/xnat/__init__.py, scripts/send_email_update.py, tests/lochness_test/mindlamp/test_mindlamp.py, tests/test_lochness.py
Number of commits from Pronet server
- to accommodate changes in the LAMP dictionary name on REDCap
- to ignore genetics and fluids
- passphrase to be passed from the shell for `systemd` settings
- to check checksum for the mindlamp downloads
=> Updates from Pronet

lochness/email/__init__.py, lochness/redcap/__init__.py, lochness/transfer/__init__.py, lochness/utils/source_check.py
Now REDCap API has been updated to specify the correct arms and fields to only pull the relevant information.
=> metadata initiation using REDCap is updated to be more effective

lochness/__init__.py, lochness/redcap/__init__.py, lochness/rpms/__init__.py
Reference: https://chr-dataflow.slack.com/archives/G01FMUND1LZ/p1657571815962639
=> Add study column to metadata

lochness/box/__init__.py, lochness/cleaner/__init__.py, lochness/email/__init__.py, lochness/mediaflux/__init__.py, lochness/mindlamp/__init__.py, lochness/redcap/__init__.py, lochness/rpms/__init__.py, lochness/tree/__init__.py, lochness/utils/path_checker.py, lochness/utils/source_check.py, lochness/xnat/__init__.py, scripts/sync.py, tests/lochness_test/cleaner/test_cleaner.py, tests/lochness_test/mediaflux/test_mediaflux.py, tests/lochness_test/rpms/test_rpms.py
Now Prescient network is running two separate lochness instances, one for mock participant and another for real participants. Configuration file now accepts a location of the CSV file with the list of mock case IDs. It also accepts a location of a CSV file with the list of IDs to ignore. Email alert functions are also updated in accordance with this change.
=> Updates in Prescient server

lochness/redcap/__init__.py, lochness/utils/path_checker.py, lochness/utils/source_check.py, tests/lochness_test/redcap/test_redcap.py, tests/lochness_test/utils/test_source_check.py
Lochness will pull if the `session_subid` field contains `AMPSCZ_[123456789]` pattern. Note `AMPSCZ_0` will not be pulled.
=> Less stringent PENN data matching
